#!/usr/bin/env python3
"""
Builds photos/manifest.js from every image sitting in this folder.

Usage:
    python3 photos/build-manifest.py

How to add your own pics:
    1. Drop the image files into the photos/ folder
       (jpg, jpeg, png, webp, gif, avif - any size, any name)
    2. Optionally give one a caption by naming it like:
           2023-goa-trip__us being idiots on a scooter.jpg
       Everything after the double underscore "__" becomes the caption.
    3. Run this script. The website picks it up automatically.

Photos are ordered by filename. Files containing "placeholder"
are always pushed to the end so your real pics come first.
"""

import json
import os
import re

PHOTO_DIR = os.path.dirname(os.path.abspath(__file__))
EXTS = {".jpg", ".jpeg", ".png", ".webp", ".gif", ".avif", ".JPG", ".JPEG", ".PNG", ".WEBP"}
OUT = os.path.join(PHOTO_DIR, "manifest.js")


def pretty_name(filename: str) -> str:
    stem = os.path.splitext(filename)[0]
    if "__" in stem:
        return stem.split("__", 1)[1].replace("_", " ").strip()
    stem = re.sub(r"[_\-]+", " ", stem)
    stem = re.sub(r"^\s*\d+\s*", "", stem)  # drop leading numbering
    stem = stem.strip()
    if stem.lower().startswith("placeholder"):
        return ""
    return stem


def main() -> None:
    files = sorted(
        f for f in os.listdir(PHOTO_DIR)
        if os.path.splitext(f)[1] in EXTS and os.path.isfile(os.path.join(PHOTO_DIR, f))
    )
    # real photos first, placeholders last
    files.sort(key=lambda f: (f.lower().startswith("placeholder"), f.lower()))

    entries = []
    for f in files:
        entries.append({
            "src": "photos/" + f,
            "caption": pretty_name(f),
            "placeholder": f.lower().startswith("placeholder"),
        })

    body = json.dumps(entries, indent=2, ensure_ascii=False)
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write("/* AUTO-GENERATED by build-manifest.py - do not edit by hand. */\n")
        fh.write("window.BIRTHDAY_PHOTOS = ")
        fh.write(body)
        fh.write(";\n")

    real = sum(1 for e in entries if not e["placeholder"])
    print(f"manifest.js written -> {real} real photo(s), {len(entries) - real} placeholder(s)")


if __name__ == "__main__":
    main()
