/* AUTO-GENERATED by build-manifest.py - do not edit by hand. */
window.BIRTHDAY_PHOTOS = [
  {
    "src": "photos/placeholder-01.jpg",
    "caption": "",
    "placeholder": true
  },
  {
    "src": "photos/placeholder-02.jpg",
    "caption": "",
    "placeholder": true
  },
  {
    "src": "photos/placeholder-03.jpg",
    "caption": "",
    "placeholder": true
  },
  {
    "src": "photos/placeholder-04.jpg",
    "caption": "",
    "placeholder": true
  },
  {
    "src": "photos/placeholder-05.jpg",
    "caption": "",
    "placeholder": true
  },
  {
    "src": "photos/placeholder-06.jpg",
    "caption": "",
    "placeholder": true
  }
];
